### ISSUE TITLE
Pause isn't active immediately

### ISSUE THREAD

**Issue by Rakambda** [om3g4zell/CityBuilderJSFML#4]
When opening the drawing section, the game is set on pause. But if you don't move your mouse after clicking, the game will still play.

**Comment by Qu3tzal** [comment]
Looks like it was waiting for another JSFML event to occur AND the hitbox to be checked to set the game on pause.
Corrected with commit 4a5a1e54401124543821d54717e1e4a8f9409f45.
Thank you !
